name: gazexplain-mac
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - scipy=1.11
  - pandas=2.2
  - scikit-image=0.22
  - h5py=3.10
  - pillow=10.2
  - matplotlib=3.8
  - tqdm=4.66
  - pytorch::pytorch=2.1
  - pytorch::torchvision=0.16
  - sentencepiece=0.1.99
  - pip:
      - accelerate==0.27.0
      - transformers==4.37.2
      - datasets==2.16.1
      - evaluate==0.4.1
      - safetensors==0.4.1
      - timm==0.9.12
      - yacs==0.1.8
